# Generated by Django 4.1.7 on 2024-08-03 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Gestions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoriee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="entree",
            name="libelle",
        ),
        migrations.AddField(
            model_name="entree",
            name="categorie",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Gestions.categoriee",
            ),
        ),
    ]
