# Generated by Django 4.1.7 on 2024-08-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gestions", "0003_alter_depense_date_alter_entree_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="abonnement",
            name="montant",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
