# Generated by Django 4.1.7 on 2024-08-11 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Gestions", "0004_abonnement_montant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configabonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "pourcentage",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("date", models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transactionabonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions_abonnement",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
