# Generated by Django 4.1.7 on 2024-08-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gestions", "0006_categories_investir"),
    ]

    operations = [
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="Mediatheques/"),
                ),
                ("contact", models.CharField(max_length=15)),
                ("presentation_text", models.TextField()),
                ("welcome_message", models.TextField()),
                ("video_url", models.URLField()),
                (
                    "pub",
                    models.ImageField(blank=True, null=True, upload_to="Mediatheques/"),
                ),
                ("email", models.CharField(max_length=50)),
                ("whatsapp", models.URLField(blank=True, null=True)),
                ("facebook", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
