# Generated by Django 4.1.7 on 2024-08-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0002_utilisateurs_profession_utilisateurs_telephone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateurs",
            name="date_inscription",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
