# Generated by Django 4.1.7 on 2024-08-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0003_utilisateurs_date_inscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateurs",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="Mediatheques/",
                verbose_name="photo de profil",
            ),
        ),
    ]
