# Generated by Django 4.1.7 on 2024-08-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Gestions", "0003_presentation_site"),
    ]

    operations = [
        migrations.AddField(
            model_name="abonnement",
            name="nature",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
